# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: go-test-coverage
        uses: vladopajic/go-test-coverage@v2.10.1

      - name: Test
        run: go test -race -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml

          # Configure action by specifying input parameters individually (option 2).
          # If you are using config file (option 1) you shouldn't use these parameters, however
          # specifting these action parameters will override appropriate config values.
          profile: cover.out
          local-prefix: github.com/org/project
          threshold-file: 80
          threshold-package: 80
          threshold-total: 95
